name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main] 
jobs:
  build:
    name: Integrate Continuously
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: sha256sum README.md
      - name: Build and Run
        run: |
          cargo run --release >> README.md
      - name: Push
        run: |
          git config user.name steven-mathew
          git config user.email ste.tho.mat@gmail.com
          git add README.txt
          git commit -m "Update Wordle of they day"
          git push
