name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main] 
jobs:
  build:
    name: Integrate Continuously
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sha256sum README.md
          echo "[![UTC timezone](https://img.shields.io/badge/timezone-UTC%2FGMT-informational)](https://www.timeanddate.com/worldclock/timezone/utc)" > README.md
          echo "---" >> README.md
          cargo run --release >> README.md
          sha256sum README.md
          git config user.name steven-mathew
          git config user.email ste.tho.mat@gmail.com
          git add README.md
          git commit -m "Update Wordle of they day"
          git push
